# .rubocop.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara

AllCops:
  NewCops: enable
  Exclude:
    - db/**/*
    - config/**/*
    - node_modules/**/*
    - bin/*
    - vendor/**/*

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Description: >-
                 A calculated magnitude based on number of assignments,
                 branches, and conditions.
  Enabled: false

Metrics/MethodLength:
  Description: 'Avoid methods longer than 10 lines of code.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#short-methods'
  Enabled: false

Style/FrozenStringLiteralComment:
  Description: >-
    Add the frozen_string_literal comment to the top of files
    to help transition from Ruby 2.3.0 to Ruby 3.0.
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Style/Attr:
  Description: 'Checks for uses of Module#attr.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#attr'
  Enabled: false

Style/ClassAndModuleChildren:
  Description: 'Checks style of children classes and modules.'
  Enabled: false

Style/ModuleFunction:
  Description: 'Checks for usage of `extend self` in modules.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#module-function'
  Enabled: false

Metrics/BlockLength:
  CountComments: true  # count full line comments?
  Max: 40
  Exclude:
    - "spec/**/*"
    - "db/migrate/*"
    - "test/factories/*"
    - "lib/tasks/import/legacy_data.rake"
    - "lib/tasks/import.rake"

Layout/LineLength:
  Description: 'Limit lines to 80 characters.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#80-character-limits'
  Max: 140
